In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

#Purpose/Goal

- To make our textual data understandable for ML mlodel/algorithuims.

##1.Lowecasing

In [2]:
sentence = 'Basically we are learning nlp. NLP is the study of ML on textual data'

In [3]:
sentence.lower()

'basically we are learning nlp. nlp is the study of ml on textual data'

In [4]:
import pandas as pd
movie_reviews = pd.read_csv('IMDB Dataset.csv')
movie_reviews

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [5]:
movie_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [6]:
reviews = movie_reviews['review']
type(reviews)

pandas.core.series.Series

In [7]:
movie_reviews['sentiment'].unique()

array(['positive', 'negative'], dtype=object)

In [8]:
movie_reviews['review'] = movie_reviews['review'].str.lower()
movie_reviews

                                                  review sentiment
0      one of the other reviewers has mentioned that ...  positive
1      a wonderful little production. <br /><br />the...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [9]:
movie_reviews['review'][0]

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

##2.Remove Html Tags

In [10]:
# importing regular expression library
import re

In [11]:
text = movie_reviews['review'][0]
text

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.<br /><br />the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.<br /><br />it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [12]:
def remove_html_tags(my_text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', my_text)

remove_html_tags(text)

"one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

In [13]:
movie_reviews['review'] = movie_reviews['review'].apply(remove_html_tags)
movie_reviews['review'][2000]

"stranded in space (1972) mst3k version - a very not good tv movie pilot, for a never to be made series, in which an astronaut finds himself trapped on earth's evil twin. having a planet of identical size and mass orbiting in the same plane as the earth, but on the opposite side of the sun, is a well worn sf chestnut - the idea is over 2,000 years old, having been invented by the ancient greeks. in this version the counter world is run as an orwellian 'perfect' society. where, for totally inexplicable reasons, everyone speaks english and drives late model american cars. after escaping from his prisonlike hospital, the disruptive earthian is chased around not southern california by tv and bad movie stalwart cameron mitchell who, like his minions, wears double breasted suits and black polo neck jumpers - a stylishly evil combination which i fully intend to adopt if ever i become a totalitarian overlord. our hero escapes several times before ending up gazing at the alien world's three moons and wondering aloud if he will ever get home - thus setting up one of those man alone in a hostile world making a new friend each week but moving on at the end of every episode shows so beloved of the industry in the 70s and 80s ('the fugitive', 'the incredible hulk', 'the littlest hobo' etc.) the curiously weirdest bit though was the title sequence. somewhere between 'stranded in space' first airing (under the title 'the stranger') in 1972 and the mst3k version in 1991 it somehow acquired some footage from the 1983 movie 'prisoners of the lost universe'. so in 1991 the opening credits for 'stranded in space' run under a few shots of three people falling into a matter transmitter and vanishing. it's a sequence that has nothing to do - even thematically - with anything that is going to follow.just to add to the nerdy b movie confusion, one of the actors in this nailed on footage, kay lenz, later appeared in a 1994 movie called 'trapped in space'. knowing this fact could never save your life but it might score you very big points and admiring looks from fellow trash movie enthusiasts - if you could ever work out a way of manoeuvring the conversation round to the point where you could casually slip it in without looking like a total idiot..."

##3.Removing URL

In [14]:
text = "We are learning https://regex101.com/ NLP"

In [15]:
def remove_url_links(text):
  pattern = re.compile(r'https?://\S+|www\.\S+')
  return pattern.sub(r'', text)

In [16]:
remove_url_links(text)

'We are learning  NLP'

In [17]:
movie_reviews['review'][40]

"it had all the clichés of movies of this type and no substance. the plot went nowhere and at the end of the movie i felt like a sucker for watching it. the production was good; however, the script and acting were b-movie quality. the casting was poor because there were good actors mixed in with crumby actors. the good actors didn't hold their own nor did they lift up the others. this movie is not worthy of more words, but i will say more to meet the minimum requirement of ten lines. james wood and cuba gooding, jr. play caricatures of themselves in other movies. if you are looking for mindless entertainment, i still wouldn't recommend this movie."

In [18]:
movie_reviews['review'] = movie_reviews['review'].apply(remove_url_links)
movie_reviews['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

##4.Deal with Punctuations

In [19]:
import string
len(string.punctuation)

32

In [20]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [21]:
exculsion_criteria = string.punctuation

In [22]:
def remove_punctuation(text):
  for char in exculsion_criteria:
    text = text.replace(char, '')
  return text

In [23]:
sample_text = "one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."
cleaned_text = remove_punctuation(sample_text)
print(cleaned_text)

one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side

In [24]:
# first 2 arguments of maketrans function is to specify mapping -- its more optimized technique
def remove_punctuation_2(sample_text):
  return sample_text.translate(str.maketrans('', '', exculsion_criteria))

In [25]:
remove_punctuation_2(sample_text)

'one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [26]:
# comparing speed of both approaches
import time
start_time = time.time()
movie_reviews['review'] = movie_reviews['review'].apply(remove_punctuation)
total_time = time.time() - start_time
total_time

1.496551275253296

In [27]:
movie_reviews = pd.read_csv('IMDB Dataset.csv')

In [28]:
start_time = time.time()
movie_reviews['review'] = movie_reviews['review'].apply(remove_punctuation_2)
total_time = time.time() - start_time
total_time

2.156122922897339

##5.Dealing with Abbreviations/Short forms

In [29]:
import pandas as pd
# we must use raw data from github source
url = 'https://raw.githubusercontent.com/rishabhverma17/sms_slang_translator/refs/heads/master/slang.txt'
Abbreviations = pd.read_csv(url, sep='=',header=None, names=['Abbreviation','Detail'])
Abbreviations

    Abbreviation                       Detail
0             A3  Anytime, Anywhere, Anyplace
1           ADIH          Another Day In Hell
2            AFK           Away From Keyboard
3          AFAIK             As Far As I Know
4           ASAP          As Soon As Possible
..           ...                          ...
99           WTG                   Way To Go!
100          WUF          Where Are You From?
101          WYD              What You Doing?
102         WYWH           Wish You Were Here
103          ZZZ       Sleeping, Bored, Tired

[104 rows x 2 columns]

In [30]:
abbv_dict = dict(zip(Abbreviations['Abbreviation'], Abbreviations['Detail']))
abbv_dict

{'A3': 'Anytime, Anywhere, Anyplace',
 'ADIH': 'Another Day In Hell',
 'AFK': 'Away From Keyboard',
 'AFAIK': 'As Far As I Know',
 'ASAP': 'As Soon As Possible',
 'ASL': 'Age, Sex, Location',
 'ATK': 'At The Keyboard',
 'ATM': 'At The Moment',
 'BAE': 'Before Anyone Else',
 'BAK': 'Back At Keyboard',
 'BBL': 'Be Back Later',
 'BBS': 'Be Back Soon',
 'BFN': 'Bye For Now',
 'B4N': 'Bye For Now',
 'BRB': 'Be Right Back',
 'BRUH': 'Bro',
 'BRT': 'Be Right There',
 'BSAAW': 'Big Smile And A Wink',
 'BTW': 'By The Way',
 'BWL': 'Bursting With Laughter',
 'CSL': 'Can’t Stop Laughing',
 'CU': 'See You',
 'CUL8R': 'See You Later',
 'CYA': 'See You',
 'DM': 'Direct Message',
 'FAQ': 'Frequently Asked Questions',
 'FC': 'Fingers Crossed',
 'FIMH': 'Forever In My Heart',
 'FOMO': 'Fear Of Missing Out',
 'FR': 'For Real',
 'FWIW': "For What It's Worth",
 'FYP': 'For You Page',
 'FYI': 'For Your Information',
 'G9': 'Genius',
 'GAL': 'Get A Life',
 'GG': 'Good Game',
 'GMTA': 'Great Minds Think Alike',
 'GN': 'Good Night',
 'GOAT': 'Greatest Of All Time',
 'GR8': 'Great!',
 'HBD': 'Happy Birthday',
 'IC': 'I See',
 'ICQ': 'I Seek You',
 'IDC': 'I Don’t Care',
 'IDK': "I Don't Know",
 'IFYP': 'I Feel Your Pain',
 'ILU': 'I Love You',
 'ILY': 'I Love You',
 'IMHO': 'In My Honest/Humble Opinion',
 'IMU': 'I Miss You',
 'IMO': 'In My Opinion',
 'IOW': 'In Other Words',
 'IRL': 'In Real Life',
 'IYKYK': 'If You Know, You Know',
 'JK': 'Just Kidding',
 'KISS': 'Keep It Simple, Stupid',
 'L': 'Loss',
 'L8R': 'Later',
 'LDR': 'Long Distance Relationship',
 'LMK': 'Let Me Know',
 'LMAO': 'Laughing My A** Off',
 'LOL': 'Laughing Out Loud',
 'LTNS': 'Long Time No See',
 'M8': 'Mate',
 'MFW': 'My Face When',
 'MID': 'Mediocre',
 'MRW': 'My Reaction When',
 'MTE': 'My Thoughts Exactly',
 'NVM': 'Never Mind',
 'NRN': 'No Reply Necessary',
 'NPC': 'Non-Player Character',
 'OIC': 'Oh I See',
 'OP': 'Overpowered',
 'PITA': 'Pain In The A**',
 'POV': 'Point Of View',
 'PRT': 'Party',
 'PRW': 'Parents Are Watching',
 'ROFL': 'Rolling On The Floor Laughing',
 'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
 'ROTFLMAO': 'Rolling On The Floor Laughing My A** Off',
 'RN': 'Right Now',
 'SK8': 'Skate',
 'STATS': 'Your Sex And Age',
 'SUS': 'Suspicious',
 'TBH': 'To Be Honest',
 'TFW': 'That Feeling When',
 'THX': 'Thank You',
 'TIME': 'Tears In My Eyes',
 'TLDR': 'Too Long, Didn’t Read',
 'TNTL': 'Trying Not To Laugh',
 'TTFN': 'Ta-Ta For Now!',
 'TTYL': 'Talk To You Later',
 'U': 'You',
 'U2': 'You Too',
 'U4E': 'Yours For Ever',
 'W': 'Win',
 'W8': 'Wait...',
 'WB': 'Welcome Back',
 'WTF': 'What The F**k',
 'WTG': 'Way To Go!',
 'WUF': 'Where Are You From?',
 'WYD': 'What You Doing?',
 'WYWH': 'Wish You Were Here',
 'ZZZ': 'Sleeping, Bored, Tired'}

In [31]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in abbv_dict:
            new_text.append(abbv_dict[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [32]:
chat_conversion('HBD he is the best')

'Happy Birthday he is the best'

In [33]:
movie_reviews['review'] = movie_reviews['review'].apply(chat_conversion)

In [34]:
chat_conversion("I'll BRB, LOL")

"I'll BRB, Laughing Out Loud"

In [35]:
my_string = "I'll BRB, LOL"
my_string.split()

["I'll", 'BRB,', 'LOL']

In [36]:
import string

In [37]:
def chat_conversion(text):
    new_text = []
    for word in text.split():
        # Separate leading/trailing punctuation from the core word
        leading_punct = ''
        while word and word[0] in string.punctuation:
            leading_punct += word[0]
            word = word[1:]

        trailing_punct = ''
        while word and word[-1] in string.punctuation:
            trailing_punct = word[-1] + trailing_punct
            word = word[:-1]

        # Check if the cleaned word (in uppercase) is an abbreviation
        if word.upper() in abbv_dict:
            new_text.append(leading_punct + abbv_dict[word.upper()] + trailing_punct)
        else:
            new_text.append(leading_punct + word + trailing_punct)
    return " ".join(new_text)

In [38]:
chat_conversion("I'll BRB, LOL")

"I'll Be Right Back, Laughing Out Loud"

##6.Dealing with Spelling mistakes

In [39]:
from textblob import TextBlob

In [40]:
incorrect_text = 'Weree is a sentncce with some spellling mistkes'
textblob = TextBlob(incorrect_text)
textblob

TextBlob("Weree is a sentncce with some spellling mistkes")

In [41]:
textblob.correct().string

'Were is a sentence with some spelling mistakes'

In [42]:
textblob = TextBlob(' '.join(movie_reviews['review'][0:4].str.lower()))
textblob

TextBlob("one of the other reviewers has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with mebr br the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordbr br it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br i would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pictures painted for mainstream audiences forget charm forget romanceoz doesnt mess around the first episode i ever saw struck me as so nasty it was surreal i couldnt say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side a wonderful little production br br the filming technique is very unassuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br the actors are extremely well chosen michael sheen not only has got all the polari but he has all the voices down pat too you can truly see the seamless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece a masterful production about one of the great masters of comedy and his life br br the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning orton and halliwell and the sets particularly of their flat with halliwells murals decorating every surface are terribly well done i thought this was a wonderful way to spend tears in my eyes on a too hot summer weekend sitting in the air conditioned theater and watching a lighthearted comedy the plot is simplistic but the dialogue is witty and the characters are likable even the well bread suspected serial killer while some may be disappointed when they realize this is not match point 2 risk addiction i thought it was proof that woody allen is still fully in control of the style many of us have grown to lovebr br this was the most id laughed at one of woodys comedies in years dare i say a decade while ive never been impressed with scarlet johanson in this she managed to tone down her sexy image and jumped right into a average but spirited young womanbr br this may not be the crown jewel of his career but it was wittier than devil wears prada and more interesting than superman a great comedy to go see with friends basically theres a family where a little boy jake thinks theres a zombie in his closet his parents are fighting all the timebr br this movie is slower than a soap opera and suddenly jake decides to become rambo and kill the zombiebr br ok first of all when youre going to make a film you must decide if its a thriller or a drama as a drama the movie is watchable parents are divorcing arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thriller spotsbr br 3 out of 10 just for the well playing parents descent dialogs as for the shots with jake just ignore them")

In [43]:
textblob.correct().string

'one of the other reviews has mentioned that after watching just 1 oz episode you be hooked they are right as this is exactly what happened with her br the first thing that struck me about oz was its brutally and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punched with regards to drugs sex or violence its is hardware in the classic use of the words br it is called oz as that is the nickname given to the onward maximum security state penitentiary it focused mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslin gangstas nations christians italians irish and more snuffles death stares podgy dealings and shady agreements are never far away br i would say the main appeal of the show is due to the fact that it goes where other shows wouldn dare forget pretty pictures painted for mainstream audiences forget charm forget romance doesn mess around the first episode i ever saw struck me as so nasty it was surrey i couldn say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphics violence not just violence but injustice crooked guards whole be sold out for a nickel inmates whole kill on order and get away with it well manner middle class inmates being turned into prison birches due to their lack of street skill or prison experience watching oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side a wonderful little production br br the filling technique is very assuming very oldtimebbc fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br the actors are extremely well chosen michael sheen not only has got all the polar but he has all the voices down pat too you can truly see the fearless editing guided by the references to williams diary entries not only is it well worth the watching but it is a terrific written and performed piece a wasteful production about one of the great masters of comedy and his life br br the realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream technique remains solid then disappears it plays on our knowledge and our senses particularly with the scenes concerning norton and halliwell and the sets particularly of their flat with halliwells morals decorating every surface are terribly well done i thought this was a wonderful way to spend tears in my eyes on a too hot summer weekend sitting in the air conditioned theater and watching a lighthearted comedy the plot is simplistic but the dialogue is witty and the characters are liable even the well bread suspected aerial killer while some may be disappointed when they realize this is not match point 2 risk addition i thought it was proof that wood allen is still fully in control of the style many of us have grown to lover br this was the most id laughed at one of woods remedies in years dare i say a decade while give never been impressed with scarlet johnson in this she managed to tone down her sex image and jumped right into a average but spirited young woman br this may not be the crown jewel of his career but it was whittier than devil wears trade and more interesting than sherman a great comedy to go see with friends basically there a family where a little boy jake thinks there a combine in his closet his parents are fighting all the timber br this movie is slower than a soap opera and suddenly jake decides to become ratio and kill the zombiebr br ok first of all when your going to make a film you must decide if its a thrilled or a drama as a drama the movie is watchable parents are diverting arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thrilled spots br 3 out of 10 just for the well playing parents descent dialogue as for the shots with jake just ignore them'

In [44]:
imdb_series = movie_reviews['review']
type(imdb_series)

pandas.core.series.Series

In [45]:
imdb_series = movie_reviews['review'][0]
type(imdb_series)

str

### Applying TextBlob Correction to Individual Reviews

We need to define a function to apply `TextBlob.correct()` to each review. Please be aware that running this on all 50,000 reviews will be very slow.

In [47]:
from textblob import TextBlob

def correct_single_review_textblob(text):
    try:
        return str(TextBlob(text).correct())
    except Exception as e:
        print(f"Error correcting text: {text[:50]}... Error: {e}")
        return text # Return original text if correction fails

# Let's test it on a few reviews to see the effect
print("Original review 0:", movie_reviews['review'][0])
print("Corrected review 0:", correct_single_review_textblob(movie_reviews['review'][0]))

print("\nOriginal review 1:", movie_reviews['review'][1])
print("Corrected review 1:", correct_single_review_textblob(movie_reviews['review'][1]))

Original review 0: One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side
Corrected review 0: One of the other reviews has mentioned that after watching just 1 Z episode you be hooked They are right as this is exactly what happened with her br The first thing that struck me about Z was its brutally and unflinching scenes of violence which set in right from the word of Trust me this is not a show for the faint hearted or timid His show pulls no punched with regards to drugs sex or violence Its is hardware in the classic use of the words br It is called of as that is the nickname given to the Scald Maximum Security State Penitentiary It focused mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Am City is home to manyAryans Muslims gangstas Nations Christians Italians Irish and more snuffles death stares podgy dealings and shady agreements are never far away br I would say the main appeal of the show is due to the fact that it goes where other shows wouldn dare Forget pretty pictures painted for mainstream audiences forget charm forget romance doesn mess around The first episode I ever saw struck me as so nasty it was surrey I couldn say I was ready for it but as I watched more I developed a taste for Z and got accustomed to the high levels of graphics violence Not just violence but injustice crooked guards whole be sold out for a nickel inmates whole kill on order and get away with it well manner middle class inmates being turned into prison birches due to their lack of street skill or prison experience Watching Z you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side

Original review 1: A wonderful little production br br The filming technique is very unassuming very oldtimeBBC fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br The actors are extremely well chosen Michael Sheen not only has got all the polari but he has all the voices down pat too You can truly see the seamless editing guided by the references to Williams diary entries not only is it well worth the watching but it is a terrificly written and performed piece A masterful production about one of the great masters of comedy and his life br br The realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream techniques remains solid then disappears It plays on our knowledge and our senses particularly with the scenes concerning Orton and Halliwell and the sets particularly of their flat with Halliwells murals decorating every surface are terribly well done
Corrected review 1: A wonderful little production br br The filling technique is very assuming very oldtimeBBC fashion and gives a comforting and sometimes discomforting sense of realism to the entire piece br br The actors are extremely well chosen Michael Sheen not only has got all the polar but he has all the voices down pat too You can truly see the fearless editing guided by the references to Williams diary entries not only is it well worth the watching but it is a terrific written and performed piece A wasteful production about one of the great masters of comedy and his life br br The realism really comes home with the little things the fantasy of the guard which rather than use the traditional dream technique remains solid then disappears It plays on our knowledge and our senses particularly with the scenes concerning Iron and Halliwell and the sets particularly of their flat with Halliwells morals decorating every surface are terribly well done

As you can see, `TextBlob` attempts to correct each word. If you wish to apply this to the entire dataset, we can create a new column in the `imdb` DataFrame, but be prepared for a long execution time. Let me know if you'd like to proceed with the full dataset, or if you'd like to explore other, potentially faster, spelling correction methods.

### Applying TextBlob Correction to the Entire Dataset

**Warning**: This operation will be very slow and may take a significant amount of time (possibly hours) to complete on 50,000 reviews. Consider running this in smaller batches if performance is a concern or if you need to monitor progress closely.

In [48]:
# print("Starting TextBlob correction for all 50,000 reviews...")
# imdb['corrected_review_textblob'] = imdb['review'].apply(correct_single_review_textblob)
# print("TextBlob correction complete. Displaying the first few corrected reviews:")
# display(imdb[['review', 'corrected_review_textblob']].head())

##7.Stop words

In [49]:
import nltk # natural languague toolkit
from nltk.corpus import stopwords

In [50]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [51]:
eng_stopwords = stopwords.words('english')
eng_stopwords

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [52]:
len(eng_stopwords)

198

In [53]:
def remove_stopwards(text):
  new_text = []
  for word in text.split():
    if word in eng_stopwords:
      new_text.append('')
    else:
      new_text.append(word)
  return " ".join(new_text)

In [54]:
clean_text = remove_stopwards('It was raining outside. So we have decided to delay our plans')
clean_text

'It  raining outside. So   decided  delay  plans'

In [55]:
movie_reviews['review'].apply(lambda text: remove_stopwards(text) if isinstance(text, str) else '')

0        One    reviewers  mentioned   watching  1 Oz e...
1        A wonderful little production br br The filmin...
2        I thought    wonderful way  spend Tears In My ...
3        Basically theres  family   little boy Jake thi...
4        Petter Matteis Love   Tears In My Eyes  Money ...
                               ...
49995    I thought  movie    right good job It wasnt  c...
49996    Bad plot bad dialogue bad acting idiotic direc...
49997    I   Catholic taught  parochial elementary scho...
49998    Im going    disagree   previous comment  side ...
49999    No one expects  Star Trek movies   high art   ...
Name: review, Length: 50000, dtype: object

In [56]:
movie_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

##8.Tokenization

- The way to convert the textual data into individual word or sentenses.

###8.1.Using Spilt function

- We only prefer this if we have a clean data available.

In [57]:
review_1st = movie_reviews['review'][0]
review_1st

'One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [58]:
type(review_1st)

str

In [59]:
# by deafult the split criteria is space
review_1st.split()

['One',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 '1',
 'Oz',
 'episode',
 'youll',
 'be',
 'hooked',
 'They',
 'are',
 'right',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'mebr',
 'br',
 'The',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'Oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'GO',
 'Trust',
 'me',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 'This',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 'sex',
 'or',
 'violence',
 'Its',
 'is',
 'hardcore',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'wordbr',
 'br',
 'It',
 'is',
 'called',
 'OZ',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'Oswald',
 'Maximum',
 'Security',
 'State',
 'Penitentary',
 'It',
 'focuses',
 'mainly',
 'on',
 'Emerald',
 'City',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 'Em',
 'City',
 'is',
 'home',
 'to',
 'manyAryans',
 'Muslims',
 'gangstas',
 'Latinos',
 'Christians',
 'Italians',
 'Irish',
 'and',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'awaybr',
 'br',
 'I',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'wouldnt',
 'dare',
 'Forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceOZ',
 'doesnt',
 'mess',
 'around',
 'The',
 'first',
 'episode',
 'I',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 'I',
 'couldnt',
 'say',
 'I',
 'was',
 'ready',
 'for',
 'it',
 'but',
 'as',
 'I',
 'watched',
 'more',
 'I',
 'developed',
 'a',
 'taste',
 'for',
 'Oz',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 'Not',
 'just',
 'violence',
 'but',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'experience',
 'Watching',
 'Oz',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewingthats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side']

In [60]:
review_1st.split('.')

['One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side']

###8.2.Regular expression

In [61]:
import re

In [62]:
review_1st = movie_reviews['review'][0]
review_1st

'One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [63]:
re.findall("[\w']+", review_1st)

<>:1: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipykernel_536/2447469642.py:1: SyntaxWarning: invalid escape sequence '\w'
  re.findall("[\w']+", review_1st)

['One',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 '1',
 'Oz',
 'episode',
 'youll',
 'be',
 'hooked',
 'They',
 'are',
 'right',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'mebr',
 'br',
 'The',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'Oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'GO',
 'Trust',
 'me',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 'This',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 'sex',
 'or',
 'violence',
 'Its',
 'is',
 'hardcore',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'wordbr',
 'br',
 'It',
 'is',
 'called',
 'OZ',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'Oswald',
 'Maximum',
 'Security',
 'State',
 'Penitentary',
 'It',
 'focuses',
 'mainly',
 'on',
 'Emerald',
 'City',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 'Em',
 'City',
 'is',
 'home',
 'to',
 'manyAryans',
 'Muslims',
 'gangstas',
 'Latinos',
 'Christians',
 'Italians',
 'Irish',
 'and',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'awaybr',
 'br',
 'I',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'wouldnt',
 'dare',
 'Forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceOZ',
 'doesnt',
 'mess',
 'around',
 'The',
 'first',
 'episode',
 'I',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 'I',
 'couldnt',
 'say',
 'I',
 'was',
 'ready',
 'for',
 'it',
 'but',
 'as',
 'I',
 'watched',
 'more',
 'I',
 'developed',
 'a',
 'taste',
 'for',
 'Oz',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 'Not',
 'just',
 'violence',
 'but',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'experience',
 'Watching',
 'Oz',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewingthats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side']

### Sentence Tokenization using Regular Expressions

In [64]:
# The regex below splits the text at a period, question mark, or exclamation mark,
# only if that punctuation is followed by a space. The `(?<=[.!?])` is a positive lookbehind
# assertion, meaning the split occurs after the punctuation but doesn't include the punctuation
# in the split delimiter itself.

sentences_re = re.split(r'(?<=[.!?])\s+', review_1st)
for i, sentence in enumerate(sentences_re):
    print(f"Sentence {i+1}: {sentence}")

Sentence 1: One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side

###8.3.By Using NLTK tokenize module

In [65]:
import nltk

In [66]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [67]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [68]:
word_tokenize(review_1st)

['One',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 '1',
 'Oz',
 'episode',
 'youll',
 'be',
 'hooked',
 'They',
 'are',
 'right',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'mebr',
 'br',
 'The',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'Oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'GO',
 'Trust',
 'me',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 'This',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 'sex',
 'or',
 'violence',
 'Its',
 'is',
 'hardcore',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'wordbr',
 'br',
 'It',
 'is',
 'called',
 'OZ',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'Oswald',
 'Maximum',
 'Security',
 'State',
 'Penitentary',
 'It',
 'focuses',
 'mainly',
 'on',
 'Emerald',
 'City',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 'Em',
 'City',
 'is',
 'home',
 'to',
 'manyAryans',
 'Muslims',
 'gangstas',
 'Latinos',
 'Christians',
 'Italians',
 'Irish',
 'and',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'awaybr',
 'br',
 'I',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'wouldnt',
 'dare',
 'Forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceOZ',
 'doesnt',
 'mess',
 'around',
 'The',
 'first',
 'episode',
 'I',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 'I',
 'couldnt',
 'say',
 'I',
 'was',
 'ready',
 'for',
 'it',
 'but',
 'as',
 'I',
 'watched',
 'more',
 'I',
 'developed',
 'a',
 'taste',
 'for',
 'Oz',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 'Not',
 'just',
 'violence',
 'but',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'experience',
 'Watching',
 'Oz',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewingthats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side']

In [69]:
sent_tokenize(review_1st)

['One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side']

In [70]:
word_tokinized = movie_reviews['review'].apply(word_tokenize)
word_tokinized

0        [One, of, the, other, reviewers, has, mentione...
1        [A, wonderful, little, production, br, br, The...
2        [I, thought, this, was, a, wonderful, way, to,...
3        [Basically, theres, a, family, where, a, littl...
4        [Petter, Matteis, Love, in, the, Tears, In, My...
                               ...
49995    [I, thought, this, movie, did, a, down, right,...
49996    [Bad, plot, bad, dialogue, bad, acting, idioti...
49997    [I, am, a, Catholic, taught, in, parochial, el...
49998    [Im, going, to, have, to, disagree, with, the,...
49999    [No, one, expects, the, Star, Trek, movies, to...
Name: review, Length: 50000, dtype: object

In [71]:
sent_tokinized = movie_reviews['review'].apply(sent_tokenize)
sent_tokinized

0        [One of the other reviewers has mentioned that...
1        [A wonderful little production br br The filmi...
2        [I thought this was a wonderful way to spend T...
3        [Basically theres a family where a little boy ...
4        [Petter Matteis Love in the Tears In My Eyes o...
                               ...
49995    [I thought this movie did a down right good jo...
49996    [Bad plot bad dialogue bad acting idiotic dire...
49997    [I am a Catholic taught in parochial elementar...
49998    [Im going to have to disagree with the previou...
49999    [No one expects the Star Trek movies to be hig...
Name: review, Length: 50000, dtype: object

In [72]:
word_tokinized[0]

['One',
 'of',
 'the',
 'other',
 'reviewers',
 'has',
 'mentioned',
 'that',
 'after',
 'watching',
 'just',
 '1',
 'Oz',
 'episode',
 'youll',
 'be',
 'hooked',
 'They',
 'are',
 'right',
 'as',
 'this',
 'is',
 'exactly',
 'what',
 'happened',
 'with',
 'mebr',
 'br',
 'The',
 'first',
 'thing',
 'that',
 'struck',
 'me',
 'about',
 'Oz',
 'was',
 'its',
 'brutality',
 'and',
 'unflinching',
 'scenes',
 'of',
 'violence',
 'which',
 'set',
 'in',
 'right',
 'from',
 'the',
 'word',
 'GO',
 'Trust',
 'me',
 'this',
 'is',
 'not',
 'a',
 'show',
 'for',
 'the',
 'faint',
 'hearted',
 'or',
 'timid',
 'This',
 'show',
 'pulls',
 'no',
 'punches',
 'with',
 'regards',
 'to',
 'drugs',
 'sex',
 'or',
 'violence',
 'Its',
 'is',
 'hardcore',
 'in',
 'the',
 'classic',
 'use',
 'of',
 'the',
 'wordbr',
 'br',
 'It',
 'is',
 'called',
 'OZ',
 'as',
 'that',
 'is',
 'the',
 'nickname',
 'given',
 'to',
 'the',
 'Oswald',
 'Maximum',
 'Security',
 'State',
 'Penitentary',
 'It',
 'focuses',
 'mainly',
 'on',
 'Emerald',
 'City',
 'an',
 'experimental',
 'section',
 'of',
 'the',
 'prison',
 'where',
 'all',
 'the',
 'cells',
 'have',
 'glass',
 'fronts',
 'and',
 'face',
 'inwards',
 'so',
 'privacy',
 'is',
 'not',
 'high',
 'on',
 'the',
 'agenda',
 'Em',
 'City',
 'is',
 'home',
 'to',
 'manyAryans',
 'Muslims',
 'gangstas',
 'Latinos',
 'Christians',
 'Italians',
 'Irish',
 'and',
 'moreso',
 'scuffles',
 'death',
 'stares',
 'dodgy',
 'dealings',
 'and',
 'shady',
 'agreements',
 'are',
 'never',
 'far',
 'awaybr',
 'br',
 'I',
 'would',
 'say',
 'the',
 'main',
 'appeal',
 'of',
 'the',
 'show',
 'is',
 'due',
 'to',
 'the',
 'fact',
 'that',
 'it',
 'goes',
 'where',
 'other',
 'shows',
 'wouldnt',
 'dare',
 'Forget',
 'pretty',
 'pictures',
 'painted',
 'for',
 'mainstream',
 'audiences',
 'forget',
 'charm',
 'forget',
 'romanceOZ',
 'doesnt',
 'mess',
 'around',
 'The',
 'first',
 'episode',
 'I',
 'ever',
 'saw',
 'struck',
 'me',
 'as',
 'so',
 'nasty',
 'it',
 'was',
 'surreal',
 'I',
 'couldnt',
 'say',
 'I',
 'was',
 'ready',
 'for',
 'it',
 'but',
 'as',
 'I',
 'watched',
 'more',
 'I',
 'developed',
 'a',
 'taste',
 'for',
 'Oz',
 'and',
 'got',
 'accustomed',
 'to',
 'the',
 'high',
 'levels',
 'of',
 'graphic',
 'violence',
 'Not',
 'just',
 'violence',
 'but',
 'injustice',
 'crooked',
 'guards',
 'wholl',
 'be',
 'sold',
 'out',
 'for',
 'a',
 'nickel',
 'inmates',
 'wholl',
 'kill',
 'on',
 'order',
 'and',
 'get',
 'away',
 'with',
 'it',
 'well',
 'mannered',
 'middle',
 'class',
 'inmates',
 'being',
 'turned',
 'into',
 'prison',
 'bitches',
 'due',
 'to',
 'their',
 'lack',
 'of',
 'street',
 'skills',
 'or',
 'prison',
 'experience',
 'Watching',
 'Oz',
 'you',
 'may',
 'become',
 'comfortable',
 'with',
 'what',
 'is',
 'uncomfortable',
 'viewingthats',
 'if',
 'you',
 'can',
 'get',
 'in',
 'touch',
 'with',
 'your',
 'darker',
 'side']

###8.4.Using Spacy

In [73]:
import spacy

In [74]:
spacy_tokenizer = spacy.load('en_core_web_sm')
spacy_tokenizer

In [75]:
review_1st = spacy_tokenizer(review_1st)
review_1st

One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side

In [76]:
for word in review_1st:
  print(word)

One
of
the
other
reviewers
has
mentioned
that
after
watching
just
1
Oz
episode
you
ll
be
hooked
They
are
right
as
this
is
exactly
what
happened
with
mebr
br
The
first
thing
that
struck
me
about
Oz
was
its
brutality
and
unflinching
scenes
of
violence
which
set
in
right
from
the
word
GO
Trust
me
this
is
not
a
show
for
the
faint
hearted
or
timid
This
show
pulls
no
punches
with
regards
to
drugs
sex
or
violence
Its
is
hardcore
in
the
classic
use
of
the
wordbr
br
It
is
called
OZ
as
that
is
the
nickname
given
to
the
Oswald
Maximum
Security
State
Penitentary
It
focuses
mainly
on
Emerald
City
an
experimental
section
of
the
prison
where
all
the
cells
have
glass
fronts
and
face
inwards
so
privacy
is
not
high
on
the
agenda
Em
City
is
home
to
manyAryans
Muslims
gangstas
Latinos
Christians
Italians
Irish
and
moreso
scuffles
death
stares
dodgy
dealings
and
shady
agreements
are
never
far
awaybr
br
I
would
say
the
main
appeal
of
the
show
is
due
to
the
fact
that
it
goes
where
other
shows
would
nt
dare
Forget
pretty
pictures
painted
for
mainstream
audiences
forget
charm
forget
romanceOZ
does
nt
mess
around
The
first
episode
I
ever
saw
struck
me
as
so
nasty
it
was
surreal
I
could
nt
say
I
was
ready
for
it
but
as
I
watched
more
I
developed
a
taste
for
Oz
and
got
accustomed
to
the
high
levels
of
graphic
violence
Not
just
violence
but
injustice
crooked
guards
who
ll
be
sold
out
for
a
nickel
inmates
who
ll
kill
on
order
and
get
away
with
it
well
mannered
middle
class
inmates
being
turned
into
prison
bitches
due
to
their
lack
of
street
skills
or
prison
experience
Watching
Oz
you
may
become
comfortable
with
what
is
uncomfortable
viewingthats
if
you
can
get
in
touch
with
your
darker
side

### SpaCy Sentence Tokenization

SpaCy automatically detects sentence boundaries when processing text. You can iterate through the `.sents` attribute of a `Doc` object to get individual sentences.

In [77]:
print('Sentences from review_1st using spaCy:')
for sentence in review_1st.sents:
  print(sentence)

Sentences from review_1st using spaCy:
One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br
The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid
This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br
I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal
I couldnt say I was ready for it
but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side

##9.Stemming

- A technique to reduce the word to its root/base word with or without proper meaning.

In [78]:
sample_text = 'singing sing sang sung sings'

In [79]:
from nltk.stem.porter import PorterStemmer

In [80]:
ps = PorterStemmer()

In [81]:
def stem_words(text):
 return " ".join([ps.stem(word) for word in text.split()])

In [82]:
stem_words(sample_text)

'sing sing sang sung sing'

In [83]:
review_1st = movie_reviews['review'][0]
review_1st

'One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [84]:
stem_words(review_1st)

'one of the other review ha mention that after watch just 1 oz episod youll be hook they are right as thi is exactli what happen with mebr br the first thing that struck me about oz wa it brutal and unflinch scene of violenc which set in right from the word go trust me thi is not a show for the faint heart or timid thi show pull no punch with regard to drug sex or violenc it is hardcor in the classic use of the wordbr br it is call oz as that is the nicknam given to the oswald maximum secur state penitentari it focus mainli on emerald citi an experiment section of the prison where all the cell have glass front and face inward so privaci is not high on the agenda em citi is home to manyaryan muslim gangsta latino christian italian irish and moreso scuffl death stare dodgi deal and shadi agreement are never far awaybr br i would say the main appeal of the show is due to the fact that it goe where other show wouldnt dare forget pretti pictur paint for mainstream audienc forget charm forget romanceoz doesnt mess around the first episod i ever saw struck me as so nasti it wa surreal i couldnt say i wa readi for it but as i watch more i develop a tast for oz and got accustom to the high level of graphic violenc not just violenc but injustic crook guard wholl be sold out for a nickel inmat wholl kill on order and get away with it well manner middl class inmat be turn into prison bitch due to their lack of street skill or prison experi watch oz you may becom comfort with what is uncomfort viewingthat if you can get in touch with your darker side'

##10.Lemmitization

- - A technique to reduce the word to its root/base word with always proper meaning.

In [85]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [86]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [87]:
from nltk.stem import WordNetLemmatizer

In [88]:
wnl = WordNetLemmatizer()

In [89]:
movie_reviews['review'][0]

'One of the other reviewers has mentioned that after watching just 1 Oz episode youll be hooked They are right as this is exactly what happened with mebr br The first thing that struck me about Oz was its brutality and unflinching scenes of violence which set in right from the word GO Trust me this is not a show for the faint hearted or timid This show pulls no punches with regards to drugs sex or violence Its is hardcore in the classic use of the wordbr br It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary It focuses mainly on Emerald City an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda Em City is home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awaybr br I would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare Forget pretty pictures painted for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw struck me as so nasty it was surreal I couldnt say I was ready for it but as I watched more I developed a taste for Oz and got accustomed to the high levels of graphic violence Not just violence but injustice crooked guards wholl be sold out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience Watching Oz you may become comfortable with what is uncomfortable viewingthats if you can get in touch with your darker side'

In [94]:
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(review_1st)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wnl.lemmatize(word,pos='a')))

Word                Lemma
One                 One
of                  of
the                 the
other               other
reviewers           reviewers
has                 has
mentioned           mentioned
that                that
after               after
watching            watching
just                just
1                   1
Oz                  Oz
episode             episode
youll               youll
be                  be
hooked              hooked
They                They
are                 are
right               right
as                  as
this                this
is                  is
exactly             exactly
what                what
happened            happened
with                with
mebr                mebr
br                  br
The                 The
first               first
thing               thing
that                that
struck              struck
me                  me
about               about
Oz                  Oz
was                 was
its                 its
brutality           brutality
and                 and
unflinching         unflinching
scenes              scenes
of                  of
violence            violence
which               which
set                 set
in                  in
right               right
from                from
the                 the
word                word
GO                  GO
Trust               Trust
me                  me
this                this
is                  is
not                 not
a                   a
show                show
for                 for
the                 the
faint               faint
hearted             hearted
or                  or
timid               timid
This                This
show                show
pulls               pulls
no                  no
punches             punches
with                with
regards             regards
to                  to
drugs               drugs
sex                 sex
or                  or
violence            violence
Its                 Its
is                  is
hardcore            hardcore
in                  in
the                 the
classic             classic
use                 use
of                  of
the                 the
wordbr              wordbr
br                  br
It                  It
is                  is
called              called
OZ                  OZ
as                  as
that                that
is                  is
the                 the
nickname            nickname
given               given
to                  to
the                 the
Oswald              Oswald
Maximum             Maximum
Security            Security
State               State
Penitentary         Penitentary
It                  It
focuses             focuses
mainly              mainly
on                  on
Emerald             Emerald
City                City
an                  an
experimental        experimental
section             section
of                  of
the                 the
prison              prison
where               where
all                 all
the                 the
cells               cells
have                have
glass               glass
fronts              fronts
and                 and
face                face
inwards             inwards
so                  so
privacy             privacy
is                  is
not                 not
high                high
on                  on
the                 the
agenda              agenda
Em                  Em
City                City
is                  is
home                home
to                  to
manyAryans          manyAryans
Muslims             Muslims
gangstas            gangstas
Latinos             Latinos
Christians          Christians
Italians            Italians
Irish               Irish
and                 and
moreso              moreso
scuffles            scuffles
death               death
stares              stares
dodgy               dodgy
dealings            dealings
and                 and
shady               shady
agreements          agreements
are                 are
never               never
far                 far
awaybr              awaybr
br                  br
I                   I
would               would
say                 say
the                 the
main                main
appeal              appeal
of                  of
the                 the
show                show
is                  is
due                 due
to                  to
the                 the
fact                fact
that                that
it                  it
goes                goes
where               where
other               other
shows               shows
wouldnt             wouldnt
dare                dare
Forget              Forget
pretty              pretty
pictures            pictures
painted             painted
for                 for
mainstream          mainstream
audiences           audiences
forget              forget
charm               charm
forget              forget
romanceOZ           romanceOZ
doesnt              doesnt
mess                mess
around              around
The                 The
first               first
episode             episode
I                   I
ever                ever
saw                 saw
struck              struck
me                  me
as                  as
so                  so
nasty               nasty
it                  it
was                 was
surreal             surreal
I                   I
couldnt             couldnt
say                 say
I                   I
was                 was
ready               ready
for                 for
it                  it
but                 but
as                  as
I                   I
watched             watched
more                more
I                   I
developed           developed
a                   a
taste               taste
for                 for
Oz                  Oz
and                 and
got                 got
accustomed          accustomed
to                  to
the                 the
high                high
levels              levels
of                  of
graphic             graphic
violence            violence
Not                 Not
just                just
violence            violence
but                 but
injustice           injustice
crooked             crooked
guards              guards
wholl               wholl
be                  be
sold                sold
out                 out
for                 for
a                   a
nickel              nickel
inmates             inmates
wholl               wholl
kill                kill
on                  on
order               order
and                 and
get                 get
away                away
with                with
it                  it
well                well
mannered            mannered
middle              middle
class               class
inmates             inmates
being               being
turned              turned
into                into
prison              prison
bitches             bitches
due                 due
to                  to
their               their
lack                lack
of                  of
street              street
skills              skills
or                  or
prison              prison
experience          experience
Watching            Watching
Oz                  Oz
you                 you
may                 may
become              become
comfortable         comfortable
with                with
what                what
is                  is
uncomfortable       uncomfortable
viewingthats        viewingthats
if                  if
you                 you
can                 can
get                 get
in                  in
touch               touch
with                with
your                your
darker              dark
side                side

In [95]:
def lemmatize_words(text):
  new_text = []
  for word in text.split():
    new_text.append(wnl.lemmatize(word,pos='v'))
  return " ".join(new_text)

lemmatize_words(review_1st)

'One of the other reviewers have mention that after watch just 1 Oz episode youll be hook They be right as this be exactly what happen with mebr br The first thing that strike me about Oz be its brutality and unflinching scenes of violence which set in right from the word GO Trust me this be not a show for the faint hearted or timid This show pull no punch with regard to drug sex or violence Its be hardcore in the classic use of the wordbr br It be call OZ as that be the nickname give to the Oswald Maximum Security State Penitentary It focus mainly on Emerald City an experimental section of the prison where all the cells have glass front and face inwards so privacy be not high on the agenda Em City be home to manyAryans Muslims gangstas Latinos Christians Italians Irish and moreso scuffle death star dodgy dealings and shady agreements be never far awaybr br I would say the main appeal of the show be due to the fact that it go where other show wouldnt dare Forget pretty picture paint for mainstream audiences forget charm forget romanceOZ doesnt mess around The first episode I ever saw strike me as so nasty it be surreal I couldnt say I be ready for it but as I watch more I develop a taste for Oz and get accustom to the high level of graphic violence Not just violence but injustice crook guard wholl be sell out for a nickel inmates wholl kill on order and get away with it well mannered middle class inmates be turn into prison bitch due to their lack of street skills or prison experience Watching Oz you may become comfortable with what be uncomfortable viewingthats if you can get in touch with your darker side'

In [96]:
stem_words(review_1st)

'one of the other review ha mention that after watch just 1 oz episod youll be hook they are right as thi is exactli what happen with mebr br the first thing that struck me about oz wa it brutal and unflinch scene of violenc which set in right from the word go trust me thi is not a show for the faint heart or timid thi show pull no punch with regard to drug sex or violenc it is hardcor in the classic use of the wordbr br it is call oz as that is the nicknam given to the oswald maximum secur state penitentari it focus mainli on emerald citi an experiment section of the prison where all the cell have glass front and face inward so privaci is not high on the agenda em citi is home to manyaryan muslim gangsta latino christian italian irish and moreso scuffl death stare dodgi deal and shadi agreement are never far awaybr br i would say the main appeal of the show is due to the fact that it goe where other show wouldnt dare forget pretti pictur paint for mainstream audienc forget charm forget romanceoz doesnt mess around the first episod i ever saw struck me as so nasti it wa surreal i couldnt say i wa readi for it but as i watch more i develop a tast for oz and got accustom to the high level of graphic violenc not just violenc but injustic crook guard wholl be sold out for a nickel inmat wholl kill on order and get away with it well manner middl class inmat be turn into prison bitch due to their lack of street skill or prison experi watch oz you may becom comfort with what is uncomfort viewingthat if you can get in touch with your darker side'