In [1]:
# from google.colab import drive
# drive.mount('/content/drive')

Mounted at /content/drive

#1. Text Representation/Vectorization Introduction

##1.1.What is feature extraction from text?

Feature extraction from text, also known as text representation or text vectorization, is the process of converting raw text data into numerical features that can be used by machine learning algorithms.

##1.2.Why is it important?
Machine learning models cannot directly process raw text. They require numerical input. Feature extraction bridges this gap by transforming human-readable text into a machine-understandable format.

##1.3.Why is this difficult to do?

Feature extraction from text is hard because human language is complex and often unclear. Unlike numbers, text does not have a direct mathematical form, so computers struggle to understand meaning. For example, a word like “bank” can mean a financial institution or the side of a river, but simple methods treat it the same. Language also includes context, sarcasm, slang, and typos, which are difficult for models to interpret correctly. On top of that, there is a huge and constantly changing vocabulary, making it harder to handle rare words and new expressions while also processing large amounts of text efficiently.

In comparison, feature extraction is easier for images and voice data because they are already in structured numerical formats. Images are made of pixel values, and voice signals are continuous waveforms, both of which can be directly processed using mathematical operations. This makes it simpler for models to extract patterns, while text requires converting unstructured language into meaningful numerical representations first, which is the main challenge.

##1.4. What is the core idea behind this?

The core idea behind text representation is simple: convert human language into numbers in a way that **keeps its meaning (semantics) intact**, this is the main goal (your “north star”). Instead of just counting words, we want models to understand how words, phrases, and sentences relate to each other. For example, “king” should be closer to “queen” than to “apple” because their meanings are related. So, the aim is to represent text such that similar meanings are close together in numerical form, allowing machines to recognize context, relationships, and intent, and ultimately perform tasks like translation, summarization, and sentiment analysis more like humans do.

##1.5. Types of Text Representation/Vectorization

Here are some important types of text representation:

*   **Bag-of-Words (BoW)**
*   **OHE**
*   **TF-IDF (Term Frequency-Inverse Document Frequency)**
*   **N-grams**
*   **Custom features**
*   **Word Embeddings** (e.g., Word2Vec, GloVe, FastText)
*   **Contextual Embeddings** (e.g., BERT, GPT, ELMo)

#2.Types of Text Representation/Vectorization

##2.1.OHE

In [2]:
import pandas as pd
movie_reviews = pd.read_csv('IMDB Dataset.csv')
movie_reviews

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [3]:
# Take 10 sample reviews
docs = movie_reviews['review'].head(10).tolist()
docs

["One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.",
 'A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams\' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master\'s of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional \'dream\' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell\'s murals decorating every surface) are terribly well done.',
 'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.',
 "Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.",
 'Petter Mattei\'s "Love in the Time of Money" is a visually stunning film to watch. Mr. Mattei offers us a vivid portrait about human relations. This is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. <br /><br />This being a variation on the Arthur Schnitzler\'s play about the same theme, the director transfers the action to the present time New York where all these different characters meet and connect. Each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. Stylishly, the film has a sophisticated luxurious look. We are taken to see how these people live and the world they live in their own habitat.<br /><br />The only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. A big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case with most of the people we encounter.<br /><br />The acting is good under Mr. Mattei\'s direction. Steve Buscemi, Rosario Dawson, Carol Kane, Michael Imperioli, Adrian Grenier, and the rest of the talented cast, make these characters come alive.<br /><br />We wish Mr. Mattei good luck and await anxiously for his next work.',
 'Probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. It just never gets old, despite my having seen it some 15 or more times in the last 25 years. Paul Lukas\' performance brings tears to my eyes, and Bette Davis, in one of her very few truly sympathetic roles, is a delight. The kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. And the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. If I had a dozen thumbs, they\'d all be "up" for this movie.',
 "I sure would like to see a resurrection of a up dated Seahunt series with the tech they have today it would bring back the kid excitement in me.I grew up on black and white TV and Seahunt with Gunsmoke were my hero's every week.You have my vote for a comeback of a new sea hunt.We need a change of pace in TV and this would work for a world of under water adventure.Oh by the way thank you for an outlet like this to view many viewpoints about TV and the many movies.So any ole way I believe I've got what I wanna say.Would be nice to read some more plus points about sea hunt.If my rhymes would be 10 lines would you let me submit,or leave me out to be in doubt and have me to quit,If this is so then I must go so lets do it.",
 "This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.<br /><br />It's truly disgraceful how far this show has fallen. The writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. I find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. How can one recognize such brilliance and then see fit to replace it with such mediocrity? I felt I must give 2 stars out of respect for the original cast that made this show such a huge success. As it is now, the show is just awful. I can't believe it's still on the air.",
 "Encouraged by the positive comments about this film on here I was looking forward to watching this film. Bad mistake. I've seen 950+ films and this is truly one of the worst of them - it's awful in almost every way: editing, pacing, storyline, 'acting,' soundtrack (the film's only song - a lame country tune - is played no less than four times). The film looks cheap and nasty and is boring in the extreme. Rarely have I been so happy to see the end credits of a film. <br /><br />The only thing that prevents me giving this a 1-score is Harvey Keitel - while this is far from his best performance he at least seems to be making a bit of an effort. One for Keitel obsessives only.",
 'If you like original gut wrenching laughter you will like this movie. If you are young or old then you will love this movie, hell even my mom liked it.<br /><br />Great Camp!!!']

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [4]:
# Build vocabulary + apply OHE (binary=True ensures 0/1)
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(binary=True, stop_words='english')
X = vectorizer.fit_transform(docs)
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 647 stored elements and shape (10, 551)>

In [5]:
list(X)

[<Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 126 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 72 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 72 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 49 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 92 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 54 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 56 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 60 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 51 stored elements and shape (1, 551)>,
 <Compressed Sparse Row sparse matrix of dtype 'int64'
 	with 15 stored elements and shape (1, 551)>]

In [6]:
# Vocabulary (Corpus contains unique words)
vocab = vectorizer.get_feature_names_out()
len(vocab)

551

In [7]:
vocab

array(['10', '15', '1990', '25', '70', '950', 'accustomed', 'acting',
       'action', 'actors', 'addiction', 'adrian', 'adventure', 'agenda',
       'agreements', 'air', 'aired', 'alive', 'allen', 'amazing',
       'anxiously', 'anymore', 'appeal', 'arguing', 'arthur', 'aryans',
       'audiences', 'average', 'await', 'awakening', 'away', 'awful',
       'bad', 'band', 'basically', 'bbc', 'believable', 'believe', 'best',
       'bette', 'big', 'bit', 'bitches', 'black', 'boogeyman', 'boring',
       'boy', 'br', 'bread', 'brilliance', 'brilliant', 'bring', 'brings',
       'brutality', 'buscemi', 'called', 'camp', 'career', 'carol',
       'case', 'cast', 'cause', 'cells', 'change', 'characters', 'charm',
       'cheap', 'children', 'chose', 'chosen', 'christians', 'city',
       'class', 'classic', 'closet', 'come', 'comeback', 'comedies',
       'comedy', 'comes', 'comfortable', 'comforting', 'comments',
       'complete', 'concerning', 'conditioned', 'connect', 'connected',
       'contact', 'continued', 'control', 'couldn', 'country', 'creator',
       'credits', 'crooked', 'crown', 'dare', 'darker', 'dated', 'davis',
       'dawson', 'dealings', 'death', 'decade', 'decide', 'decides',
       'decline', 'decorating', 'dedication', 'delight', 'descent',
       'despite', 'developed', 'devil', 'dialogs', 'dialogue', 'diary',
       'different', 'direction', 'director', 'disappears', 'disappointed',
       'discerns', 'discomforting', 'disgraceful', 'divorcing', 'dodgy',
       'doesn', 'doubt', 'dozen', 'drama', 'dream', 'dressed', 'dropped',
       'drugs', 'editing', 'effort', 'em', 'emerald', 'encounter',
       'encouraged', 'end', 'entertaining', 'entire', 'entries',
       'episode', 'exactly', 'excitement', 'expected', 'experience',
       'experimental', 'extreme', 'extremely', 'eyes', 'face', 'fact',
       'faint', 'fallen', 'family', 'fantasy', 'far', 'fashion',
       'favorite', 'felt', 'fighting', 'film', 'filming', 'films', 'fit',
       'flat', 'focuses', 'followed', 'forget', 'forward', 'fresh',
       'friends', 'fronts', 'fulfillment', 'fully', 'fun', 'funny',
       'gangstas', 'gets', 'given', 'gives', 'giving', 'glass', 'goes',
       'going', 'good', 'got', 'grandma', 'graphic', 'great', 'grenier',
       'grew', 'grown', 'guard', 'guards', 'guest', 'guided', 'gunsmoke',
       'gut', 'habitat', 'hacks', 'halliwell', 'hand', 'happened',
       'happening', 'happy', 'hard', 'hardcore', 'harvey', 'having',
       'hearted', 'hell', 'hero', 'high', 'home', 'hooked', 'hosts',
       'hot', 'huge', 'human', 'hunt', 'idea', 'ignore', 'image',
       'imperioli', 'impressed', 'inhabits', 'injustice', 'inmates',
       'innovative', 'instead', 'interesting', 'inwards', 'irish',
       'italians', 'jake', 'jewel', 'johanson', 'jumped', 'just', 'kane',
       'keitel', 'kid', 'kids', 'kill', 'killer', 'know', 'knowledge',
       'lack', 'lame', 'latinos', 'laughed', 'laughter', 'leave', 'let',
       'lets', 'levels', 'life', 'light', 'likable', 'like', 'liked',
       'lines', 'little', 'live', 'll', 'loneliness', 'look', 'looking',
       'looks', 'love', 'luck', 'lukas', 'luxurious', 'main', 'mainly',
       'mainstream', 'make', 'makes', 'making', 'managed', 'mannered',
       'master', 'masterful', 'match', 'mattei', 'maximum', 'meaningless',
       'mediocrity', 'meet', 'mentioned', 'mess', 'michael', 'middle',
       'midgets', 'mildly', 'mistake', 'mom', 'money', 'mother', 'movie',
       'movies', 'mr', 'murals', 'muslims', 'nasty', 'need', 'new',
       'nice', 'nickel', 'nickname', 'noble', 'obsessives', 'offers',
       'oh', 'ok', 'old', 'ole', 'opera', 'order', 'original', 'orton',
       'oswald', 'outlet', 'oz', 'pace', 'pacing', 'painfully', 'painted',
       'parents', 'particularly', 'pat', 'paul', 'penitentary', 'people',
       'performance', 'performances', 'performed', 'person', 'petter',
       'picture', 'pictures', 'piece', 'place', 'play', 'played',
       'playing', 'plays', 'plot', 'plus', 'point', 'points', 'polari',
       'portrait', 'positive', 'power', 'prada', 'preachy', 'present',
       'pretty', 'prevents', 'previous', 'prison', 'privacy', 'probably',
       'production', 'proof', 'pulls', 'punches', 'quit', 'rambo',
       'rarely', 'read', 'ready', 'real', 'realism', 'realize', 'really',
       'recognize', 'references', 'regards', 'relations', 'remains',
       'replace', 'respect', 'respite', 'rest', 'resurrection',
       'reviewers', 'rhymes', 'right', 'risk', 'roles', 'romance', 'roof',
       'rosario', 'ruins', 'sacrifice', 'saw', 'say', 'says', 'scarlet',
       'scenes', 'schnitzler', 'score', 'scuffles', 'sea', 'seahunt',
       'seamless', 'section', 'security', 'seen', 'selected',
       'selflessness', 'sense', 'senses', 'serial', 'series', 'set',
       'sets', 'sex', 'sexy', 'shady', 'sheen', 'shots', 'shows',
       'similar', 'simplistic', 'sitting', 'situations', 'skills', 'slow',
       'slower', 'soap', 'sold', 'solid', 'song', 'sophisticated',
       'souls', 'soundtrack', 'spend', 'spirited', 'spots', 'stages',
       'stares', 'stars', 'startling', 'state', 'steve', 'story',
       'storyline', 'street', 'struck', 'stunning', 'style', 'stylishly',
       'submit', 'success', 'suddenly', 'summer', 'superman', 'sure',
       'surface', 'surreal', 'suspected', 'sympathetic', 'taken',
       'talented', 'taste', 'tears', 'tech', 'technique', 'techniques',
       'telling', 'terribly', 'terrificly', 'thank', 'thats', 'theater',
       'theme', 'thing', 'things', 'thinks', 'thought', 'thriller',
       'thumbs', 'time', 'times', 'timid', 'today', 'tone', 'totally',
       'touch', 'traditional', 'transfers', 'truly', 'trust', 'tune',
       'turned', 'tv', 'unassuming', 'uncomfortable', 'unflinching',
       'use', 'variation', 've', 'view', 'viewing', 'viewpoints',
       'violence', 'visually', 'vivid', 'voices', 'vote', 'wanna',
       'waste', 'watch', 'watchable', 'watched', 'watching', 'water',
       'way', 'wears', 'week', 'weekend', 'white', 'williams', 'wish',
       'wittier', 'witty', 'woman', 'wonderful', 'woody', 'word', 'work',
       'world', 'worst', 'worth', 'wouldn', 'wrenching', 'writing',
       'written', 'years', 'york', 'young', 'zombie'], dtype=object)

In [8]:
# OHE matrix (Documents representation)
ohe_df = pd.DataFrame(X.toarray(), columns=vocab)
ohe_df

,10,15,1990,25,70,950,accustomed,acting,action,actors,...,worst,worth,wouldn,wrenching,writing,written,years,york,young,zombie
0,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,1,0,0
5,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,0
8,0,0,0,0,0,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0

In [9]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10, 11])
array1 * array2

ValueError: operands could not be broadcast together with shapes (5,) (6,)

- Pros

      Intutive and very simple to understand
      Easy to code

- Cons

      It generates Sparse data which leads to overfitting.
      It can't handled the shapes which will be formed as disliked arrays.
      OOV (Out of Vocab) Problem
      Semantic meaning is not captured
      Order of words does'nt matter

##2.2.Bag of words (BOW)

-  Better to use in text classification problem!!
- The semantic meaning of words doesn't capture directly.

In [10]:
# BoW (counts instead of binary)
vectorizer = CountVectorizer(stop_words='english', binary = False)
X = vectorizer.fit_transform(docs)

# Vocabulary
vocab = vectorizer.get_feature_names_out()

# BoW matrix
bow_df = pd.DataFrame(X.toarray(), columns=vocab)
bow_df

,10,15,1990,25,70,950,accustomed,acting,action,actors,...,worst,worth,wouldn,wrenching,writing,written,years,york,young,zombie
0,0,0,0,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,0,1,0,0,0,1,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0
3,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2
4,0,0,0,0,0,0,0,1,1,0,...,0,0,0,0,0,0,0,1,0,0
5,0,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,1,0,1,0,0,0,0,0,...,0,0,1,0,1,0,1,0,0,0
8,0,0,0,0,0,1,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0

In [11]:
bow_df.shape

(10, 551)

In [12]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [13]:
len(vocab)

551

In [14]:
# to know how many times each unique word appear in given corpus
word_counts = bow_df.sum().sort_values(ascending=False)
print(word_counts.head(20))

br            36
film           9
movie          8
time           7
oz             6
like           6
just           6
watching       5
way            5
mattei         4
violence       4
truly          4
say            4
jake           4
thing          3
characters     3
right          3
cast           3
bad            3
believe        3
dtype: int64

- Pros

      Simple and intutive
      disliked arrays formed will not be able to compute later
      OOV problem is solved (new words will be ignored)
      Semantic menaning is captured indirectly based on the distnace present between the vectors.

  - Cons

        Sparsity (a lot of zeros matrix) => overfitting
        OOV (we are merely ignoring the new words)
        order of words still doesn't matter
        Similar but opposite sentenses consider same here.

##2.3.N-grams Technique

In [15]:
vocab

array(['10', '15', '1990', '25', '70', '950', 'accustomed', 'acting',
       'action', 'actors', 'addiction', 'adrian', 'adventure', 'agenda',
       'agreements', 'air', 'aired', 'alive', 'allen', 'amazing',
       'anxiously', 'anymore', 'appeal', 'arguing', 'arthur', 'aryans',
       'audiences', 'average', 'await', 'awakening', 'away', 'awful',
       'bad', 'band', 'basically', 'bbc', 'believable', 'believe', 'best',
       'bette', 'big', 'bit', 'bitches', 'black', 'boogeyman', 'boring',
       'boy', 'br', 'bread', 'brilliance', 'brilliant', 'bring', 'brings',
       'brutality', 'buscemi', 'called', 'camp', 'career', 'carol',
       'case', 'cast', 'cause', 'cells', 'change', 'characters', 'charm',
       'cheap', 'children', 'chose', 'chosen', 'christians', 'city',
       'class', 'classic', 'closet', 'come', 'comeback', 'comedies',
       'comedy', 'comes', 'comfortable', 'comforting', 'comments',
       'complete', 'concerning', 'conditioned', 'connect', 'connected',
       'contact', 'continued', 'control', 'couldn', 'country', 'creator',
       'credits', 'crooked', 'crown', 'dare', 'darker', 'dated', 'davis',
       'dawson', 'dealings', 'death', 'decade', 'decide', 'decides',
       'decline', 'decorating', 'dedication', 'delight', 'descent',
       'despite', 'developed', 'devil', 'dialogs', 'dialogue', 'diary',
       'different', 'direction', 'director', 'disappears', 'disappointed',
       'discerns', 'discomforting', 'disgraceful', 'divorcing', 'dodgy',
       'doesn', 'doubt', 'dozen', 'drama', 'dream', 'dressed', 'dropped',
       'drugs', 'editing', 'effort', 'em', 'emerald', 'encounter',
       'encouraged', 'end', 'entertaining', 'entire', 'entries',
       'episode', 'exactly', 'excitement', 'expected', 'experience',
       'experimental', 'extreme', 'extremely', 'eyes', 'face', 'fact',
       'faint', 'fallen', 'family', 'fantasy', 'far', 'fashion',
       'favorite', 'felt', 'fighting', 'film', 'filming', 'films', 'fit',
       'flat', 'focuses', 'followed', 'forget', 'forward', 'fresh',
       'friends', 'fronts', 'fulfillment', 'fully', 'fun', 'funny',
       'gangstas', 'gets', 'given', 'gives', 'giving', 'glass', 'goes',
       'going', 'good', 'got', 'grandma', 'graphic', 'great', 'grenier',
       'grew', 'grown', 'guard', 'guards', 'guest', 'guided', 'gunsmoke',
       'gut', 'habitat', 'hacks', 'halliwell', 'hand', 'happened',
       'happening', 'happy', 'hard', 'hardcore', 'harvey', 'having',
       'hearted', 'hell', 'hero', 'high', 'home', 'hooked', 'hosts',
       'hot', 'huge', 'human', 'hunt', 'idea', 'ignore', 'image',
       'imperioli', 'impressed', 'inhabits', 'injustice', 'inmates',
       'innovative', 'instead', 'interesting', 'inwards', 'irish',
       'italians', 'jake', 'jewel', 'johanson', 'jumped', 'just', 'kane',
       'keitel', 'kid', 'kids', 'kill', 'killer', 'know', 'knowledge',
       'lack', 'lame', 'latinos', 'laughed', 'laughter', 'leave', 'let',
       'lets', 'levels', 'life', 'light', 'likable', 'like', 'liked',
       'lines', 'little', 'live', 'll', 'loneliness', 'look', 'looking',
       'looks', 'love', 'luck', 'lukas', 'luxurious', 'main', 'mainly',
       'mainstream', 'make', 'makes', 'making', 'managed', 'mannered',
       'master', 'masterful', 'match', 'mattei', 'maximum', 'meaningless',
       'mediocrity', 'meet', 'mentioned', 'mess', 'michael', 'middle',
       'midgets', 'mildly', 'mistake', 'mom', 'money', 'mother', 'movie',
       'movies', 'mr', 'murals', 'muslims', 'nasty', 'need', 'new',
       'nice', 'nickel', 'nickname', 'noble', 'obsessives', 'offers',
       'oh', 'ok', 'old', 'ole', 'opera', 'order', 'original', 'orton',
       'oswald', 'outlet', 'oz', 'pace', 'pacing', 'painfully', 'painted',
       'parents', 'particularly', 'pat', 'paul', 'penitentary', 'people',
       'performance', 'performances', 'performed', 'person', 'petter',
       'picture', 'pictures', 'piece', 'place', 'play', 'played',
       'playing', 'plays', 'plot', 'plus', 'point', 'points', 'polari',
       'portrait', 'positive', 'power', 'prada', 'preachy', 'present',
       'pretty', 'prevents', 'previous', 'prison', 'privacy', 'probably',
       'production', 'proof', 'pulls', 'punches', 'quit', 'rambo',
       'rarely', 'read', 'ready', 'real', 'realism', 'realize', 'really',
       'recognize', 'references', 'regards', 'relations', 'remains',
       'replace', 'respect', 'respite', 'rest', 'resurrection',
       'reviewers', 'rhymes', 'right', 'risk', 'roles', 'romance', 'roof',
       'rosario', 'ruins', 'sacrifice', 'saw', 'say', 'says', 'scarlet',
       'scenes', 'schnitzler', 'score', 'scuffles', 'sea', 'seahunt',
       'seamless', 'section', 'security', 'seen', 'selected',
       'selflessness', 'sense', 'senses', 'serial', 'series', 'set',
       'sets', 'sex', 'sexy', 'shady', 'sheen', 'shots', 'shows',
       'similar', 'simplistic', 'sitting', 'situations', 'skills', 'slow',
       'slower', 'soap', 'sold', 'solid', 'song', 'sophisticated',
       'souls', 'soundtrack', 'spend', 'spirited', 'spots', 'stages',
       'stares', 'stars', 'startling', 'state', 'steve', 'story',
       'storyline', 'street', 'struck', 'stunning', 'style', 'stylishly',
       'submit', 'success', 'suddenly', 'summer', 'superman', 'sure',
       'surface', 'surreal', 'suspected', 'sympathetic', 'taken',
       'talented', 'taste', 'tears', 'tech', 'technique', 'techniques',
       'telling', 'terribly', 'terrificly', 'thank', 'thats', 'theater',
       'theme', 'thing', 'things', 'thinks', 'thought', 'thriller',
       'thumbs', 'time', 'times', 'timid', 'today', 'tone', 'totally',
       'touch', 'traditional', 'transfers', 'truly', 'trust', 'tune',
       'turned', 'tv', 'unassuming', 'uncomfortable', 'unflinching',
       'use', 'variation', 've', 'view', 'viewing', 'viewpoints',
       'violence', 'visually', 'vivid', 'voices', 'vote', 'wanna',
       'waste', 'watch', 'watchable', 'watched', 'watching', 'water',
       'way', 'wears', 'week', 'weekend', 'white', 'williams', 'wish',
       'wittier', 'witty', 'woman', 'wonderful', 'woody', 'word', 'work',
       'world', 'worst', 'worth', 'wouldn', 'wrenching', 'writing',
       'written', 'years', 'york', 'young', 'zombie'], dtype=object)

In [16]:
len(vocab)

551

In [17]:
print(vocab)

['10' '15' '1990' '25' '70' '950' 'accustomed' 'acting' 'action' 'actors'
 'addiction' 'adrian' 'adventure' 'agenda' 'agreements' 'air' 'aired'
 'alive' 'allen' 'amazing' 'anxiously' 'anymore' 'appeal' 'arguing'
 'arthur' 'aryans' 'audiences' 'average' 'await' 'awakening' 'away'
 'awful' 'bad' 'band' 'basically' 'bbc' 'believable' 'believe' 'best'
 'bette' 'big' 'bit' 'bitches' 'black' 'boogeyman' 'boring' 'boy' 'br'
 'bread' 'brilliance' 'brilliant' 'bring' 'brings' 'brutality' 'buscemi'
 'called' 'camp' 'career' 'carol' 'case' 'cast' 'cause' 'cells' 'change'
 'characters' 'charm' 'cheap' 'children' 'chose' 'chosen' 'christians'
 'city' 'class' 'classic' 'closet' 'come' 'comeback' 'comedies' 'comedy'
 'comes' 'comfortable' 'comforting' 'comments' 'complete' 'concerning'
 'conditioned' 'connect' 'connected' 'contact' 'continued' 'control'
 'couldn' 'country' 'creator' 'credits' 'crooked' 'crown' 'dare' 'darker'
 'dated' 'davis' 'dawson' 'dealings' 'death' 'decade' 'decide' 'decides'
 'decline' 'decorating' 'dedication' 'delight' 'descent' 'despite'
 'developed' 'devil' 'dialogs' 'dialogue' 'diary' 'different' 'direction'
 'director' 'disappears' 'disappointed' 'discerns' 'discomforting'
 'disgraceful' 'divorcing' 'dodgy' 'doesn' 'doubt' 'dozen' 'drama' 'dream'
 'dressed' 'dropped' 'drugs' 'editing' 'effort' 'em' 'emerald' 'encounter'
 'encouraged' 'end' 'entertaining' 'entire' 'entries' 'episode' 'exactly'
 'excitement' 'expected' 'experience' 'experimental' 'extreme' 'extremely'
 'eyes' 'face' 'fact' 'faint' 'fallen' 'family' 'fantasy' 'far' 'fashion'
 'favorite' 'felt' 'fighting' 'film' 'filming' 'films' 'fit' 'flat'
 'focuses' 'followed' 'forget' 'forward' 'fresh' 'friends' 'fronts'
 'fulfillment' 'fully' 'fun' 'funny' 'gangstas' 'gets' 'given' 'gives'
 'giving' 'glass' 'goes' 'going' 'good' 'got' 'grandma' 'graphic' 'great'
 'grenier' 'grew' 'grown' 'guard' 'guards' 'guest' 'guided' 'gunsmoke'
 'gut' 'habitat' 'hacks' 'halliwell' 'hand' 'happened' 'happening' 'happy'
 'hard' 'hardcore' 'harvey' 'having' 'hearted' 'hell' 'hero' 'high' 'home'
 'hooked' 'hosts' 'hot' 'huge' 'human' 'hunt' 'idea' 'ignore' 'image'
 'imperioli' 'impressed' 'inhabits' 'injustice' 'inmates' 'innovative'
 'instead' 'interesting' 'inwards' 'irish' 'italians' 'jake' 'jewel'
 'johanson' 'jumped' 'just' 'kane' 'keitel' 'kid' 'kids' 'kill' 'killer'
 'know' 'knowledge' 'lack' 'lame' 'latinos' 'laughed' 'laughter' 'leave'
 'let' 'lets' 'levels' 'life' 'light' 'likable' 'like' 'liked' 'lines'
 'little' 'live' 'll' 'loneliness' 'look' 'looking' 'looks' 'love' 'luck'
 'lukas' 'luxurious' 'main' 'mainly' 'mainstream' 'make' 'makes' 'making'
 'managed' 'mannered' 'master' 'masterful' 'match' 'mattei' 'maximum'
 'meaningless' 'mediocrity' 'meet' 'mentioned' 'mess' 'michael' 'middle'
 'midgets' 'mildly' 'mistake' 'mom' 'money' 'mother' 'movie' 'movies' 'mr'
 'murals' 'muslims' 'nasty' 'need' 'new' 'nice' 'nickel' 'nickname'
 'noble' 'obsessives' 'offers' 'oh' 'ok' 'old' 'ole' 'opera' 'order'
 'original' 'orton' 'oswald' 'outlet' 'oz' 'pace' 'pacing' 'painfully'
 'painted' 'parents' 'particularly' 'pat' 'paul' 'penitentary' 'people'
 'performance' 'performances' 'performed' 'person' 'petter' 'picture'
 'pictures' 'piece' 'place' 'play' 'played' 'playing' 'plays' 'plot'
 'plus' 'point' 'points' 'polari' 'portrait' 'positive' 'power' 'prada'
 'preachy' 'present' 'pretty' 'prevents' 'previous' 'prison' 'privacy'
 'probably' 'production' 'proof' 'pulls' 'punches' 'quit' 'rambo' 'rarely'
 'read' 'ready' 'real' 'realism' 'realize' 'really' 'recognize'
 'references' 'regards' 'relations' 'remains' 'replace' 'respect'
 'respite' 'rest' 'resurrection' 'reviewers' 'rhymes' 'right' 'risk'
 'roles' 'romance' 'roof' 'rosario' 'ruins' 'sacrifice' 'saw' 'say' 'says'
 'scarlet' 'scenes' 'schnitzler' 'score' 'scuffles' 'sea' 'seahunt'
 'seamless' 'section' 'security' 'seen' 'selected' 'selflessness' 'sense'
 'senses' 'serial' 'series' 'set' 'sets' 'sex' 'sexy' 'shady' 'sheen'
 'shots' 'shows' 'similar' 'simplistic' 'sitting' 'situations' 'skills'
 'slow' 'slower' 'soap' 'sold' 'solid' 'song' 'sophisticated' 'souls'
 'soundtrack' 'spend' 'spirited' 'spots' 'stages' 'stares' 'stars'
 'startling' 'state' 'steve' 'story' 'storyline' 'street' 'struck'
 'stunning' 'style' 'stylishly' 'submit' 'success' 'suddenly' 'summer'
 'superman' 'sure' 'surface' 'surreal' 'suspected' 'sympathetic' 'taken'
 'talented' 'taste' 'tears' 'tech' 'technique' 'techniques' 'telling'
 'terribly' 'terrificly' 'thank' 'thats' 'theater' 'theme' 'thing'
 'things' 'thinks' 'thought' 'thriller' 'thumbs' 'time' 'times' 'timid'
 'today' 'tone' 'totally' 'touch' 'traditional' 'transfers' 'truly'
 'trust' 'tune' 'turned' 'tv' 'unassuming' 'uncomfortable' 'unflinching'
 'use' 'variation' 've' 'view' 'viewing' 'viewpoints' 'violence'
 'visually' 'vivid' 'voices' 'vote' 'wanna' 'waste' 'watch' 'watchable'
 'watched' 'watching' 'water' 'way' 'wears' 'week' 'weekend' 'white'
 'williams' 'wish' 'wittier' 'witty' 'woman' 'wonderful' 'woody' 'word'
 'work' 'world' 'worst' 'worth' 'wouldn' 'wrenching' 'writing' 'written'
 'years' 'york' 'young' 'zombie']

In [18]:
# N-grams (grams instead of words)
vectorizer = CountVectorizer(stop_words='english', ngram_range=(1,3))
X = vectorizer.fit_transform(docs)

# Vocabulary
vocab = vectorizer.get_feature_names_out()

# BoW matrix
bow_df = pd.DataFrame(X.toarray(), columns=vocab)
bow_df

,10,10 just,10 just playing,10 lines,10 lines let,15,15 times,15 times 25,1990,1990 really,...,young,young old,young old love,young woman,young woman br,zombie,zombie br,zombie br br,zombie closet,zombie closet parents
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,1,0,0,0,0,0
3,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,2,1,1,1,1
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1,0,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,...,1,1,1,0,0,0,0,0,0,0

In [19]:
bow_df.shape

(10, 2015)

- Pros

      Simple and easy to code
      Able to capture the semantic meaning to some extent.
      We are able to distinguish between similar but opposite statements.

- Cons

       Overfitting because of sparsity
       N-dim is increased compared to mono-gram/BOW which will increase the training time of model.
       OOV is still there (we are just ignoring the new words).

##2.4.TF-IDF (Term Frequency-Inverse Document Frequency)

- When we have to use this techq?

    `Lets say if one word is present more in 1 doc compare to other docs (corpus), we should be given more weightage to this word`

###What does high and low tf idf value means for a word?

- **High TF-IDF value** for a word means that the word is very relevant and significant to a specific document within the corpus. It implies the word appears frequently in that particular document (high Term Frequency) but is relatively rare across other documents in the corpus (high Inverse Document Frequency). This combination makes the word a good distinguishing feature for that document.

- **Low TF-IDF value** for a word means that the word is either not very frequent in the specific document.
Very common across many documents in the corpus (e.g., stop words like 'the', 'is', 'a'), even if it appears frequently in the current document. Words with low TF-IDF values are generally not good discriminators for a document, as they don't help differentiate it from others.

###Why use log to calculate IDF term?

- Imagine you're ranking how "special" a word is by how rare it is. Without the log, a word appearing in 1 out of 10,000 documents would be judged 100 times more important than a word appearing in 100 documents — but intuitively it's not *100 times* more meaningful, just somewhat more. Rare words are so much rarer than common ones that this raw ratio explodes, and a single super-rare word (often just a typo or a name) would completely drown out everything else in the score. The log squashes that runaway growth into gentle, sensible steps — so rarity still boosts a word's weight, but with diminishing returns instead of an exploding one, letting the term-frequency part of the formula actually still matter.

https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html

In [20]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf_idf = TfidfVectorizer()
X = tf_idf.fit_transform(docs).toarray()
vocab = tf_idf.get_feature_names_out()
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.04922065,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.07220094, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.07095822, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.16036163, 0.        ,
        0.        ]])

In [21]:
# BoW matrix
tfidf_df = pd.DataFrame(X, columns=vocab)
tfidf_df

,10,15,1990,25,70,950,about,accustomed,acting,action,...,wouldn,wrenching,writing,written,years,york,you,young,your,zombie
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.029228,0.049221,0.000000,0.000000,...,0.041842,0.00000,0.000000,0.000000,0.000000,0.000000,0.087685,0.000000,0.049221,0.00000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.044484,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.074911,0.000000,0.000000,0.044484,0.000000,0.000000,0.00000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.063167,0.000000,0.000000,0.072201,0.000000,0.00000
3,0.073044,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.102048,0.000000,0.000000,0.17185
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.066170,0.000000,0.047363,0.055716,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.055716,0.000000,0.000000,0.000000,0.00000
5,0.000000,0.104317,0.000000,0.104317,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.077584,0.000000,0.000000,0.000000,0.000000,0.00000
6,0.066756,0.000000,0.000000,0.000000,0.000000,0.00000,0.093264,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.139896,0.000000,0.000000,0.00000
7,0.000000,0.000000,0.070958,0.000000,0.070958,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.060321,0.00000,0.070958,0.000000,0.052774,0.000000,0.000000,0.000000,0.000000,0.00000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.09798,0.058183,0.000000,0.083292,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.18864,0.000000,0.000000,0.000000,0.000000,0.448075,0.160362,0.000000,0.00000

In [22]:
X.shape

(10, 675)

In [23]:
50000/10

5000.0

In [24]:
docs[2]

'I thought this was a wonderful way to spend time on a too hot summer weekend, sitting in the air conditioned theater and watching a light-hearted comedy. The plot is simplistic, but the dialogue is witty and the characters are likable (even the well bread suspected serial killer). While some may be disappointed when they realize this is not Match Point 2: Risk Addiction, I thought it was proof that Woody Allen is still fully in control of the style many of us have grown to love.<br /><br />This was the most I\'d laughed at one of Woody\'s comedies in years (dare I say a decade?). While I\'ve never been impressed with Scarlet Johanson, in this she managed to tone down her "sexy" image and jumped right into a average, but spirited young woman.<br /><br />This may not be the crown jewel of his career, but it was wittier than "Devil Wears Prada" and more interesting than "Superman" a great comedy to go see with friends.'

In [25]:
X[2]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.07220094, 0.        , 0.        ,
       0.        , 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.13757753, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.03770286, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07220094, 0.        ,
       0.08493315, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08280285, 0.        , 0.07220094, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.15081145, 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.13678354, 0.        ,
       0.        , 0.        , 0.        , 0.08493315, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07220094, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.08493315, 0.14440187,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08493315, 0.07220094, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.        , 0.08493315, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.08493315, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07220094, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.07220094, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.        , 0.        , 0.        , 0.08493315,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06316729, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.06316729, 0.        ,
       0.        , 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05043508, 0.        , 0.        , 0.07220094, 0.        ,
       0.07220094, 0.        , 0.        , 0.        , 0.05043508,
       0.        , 0.        , 0.        , 0.08493315, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08493315, 0.        , 0.08493315, 0.15081145,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.07220094, 0.        , 0.        , 0.13757753,
       0.07540572, 0.        , 0.        , 0.        , 0.08493315,
       0.08493315, 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.08493315, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.08493315,
       0.08493315, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06316729, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08493315, 0.        , 0.06316729,
       0.        , 0.        , 0.08493315, 0.        , 0.        ,
       0.14440187, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.05616025,
       0.07220094, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06316729, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.09118902,
       0.        , 0.        , 0.13757753, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.04140143,
       0.04140143, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08493315, 0.        , 0.07220094,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08493315, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.07220094, 0.08493315, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.06316729, 0.        , 0.08493315, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.04140143, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.        , 0.        , 0.        , 0.        ,
       0.08493315, 0.        , 0.08493315, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.08493315,
       0.        , 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.05616025, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08493315, 0.08493315, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07220094, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.08493315, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.08493315, 0.08493315, 0.        ,
       0.        , 0.        , 0.08493315, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.10087015,
       0.        , 0.04559451, 0.        , 0.27515507, 0.08493315,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.05043508, 0.        , 0.        , 0.        ,
       0.17197192, 0.1698663 , 0.        , 0.        , 0.04559451,
       0.        , 0.        , 0.13757753, 0.        , 0.08493315,
       0.07220094, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.07220094, 0.        , 0.        , 0.06316729, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.22464098,
       0.        , 0.        , 0.        , 0.        , 0.05616025,
       0.        , 0.05616025, 0.        , 0.08493315, 0.        ,
       0.08493315, 0.05616025, 0.        , 0.        , 0.06316729,
       0.        , 0.        , 0.14440187, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.08280285, 0.08493315,
       0.08493315, 0.08493315, 0.07220094, 0.1698663 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.06316729,
       0.        , 0.        , 0.07220094, 0.        , 0.        ])

In [26]:
vocab = tf_idf.get_feature_names_out()
vocab

array(['10', '15', '1990', '25', '70', '950', 'about', 'accustomed',
       'acting', 'action', 'actors', 'addiction', 'adrian', 'adventure',
       'after', 'agenda', 'agreements', 'air', 'aired', 'alive', 'all',
       'allen', 'almost', 'also', 'amazing', 'an', 'and', 'another',
       'anxiously', 'any', 'anymore', 'appeal', 'are', 'arguing',
       'around', 'arthur', 'aryans', 'as', 'at', 'audiences', 'average',
       'await', 'awakening', 'away', 'awful', 'back', 'bad', 'band',
       'basically', 'bbc', 'be', 'become', 'been', 'being', 'believable',
       'believe', 'best', 'bette', 'big', 'bit', 'bitches', 'black',
       'boogeyman', 'boring', 'boy', 'br', 'bread', 'brilliance',
       'brilliant', 'bring', 'brings', 'brutality', 'buscemi', 'but',
       'by', 'called', 'camp', 'can', 'career', 'carol', 'case', 'cast',
       'cause', 'cells', 'change', 'characters', 'charm', 'cheap',
       'children', 'chose', 'chosen', 'christians', 'city', 'class',
       'classic', 'closet', 'come', 'comeback', 'comedies', 'comedy',
       'comes', 'comfortable', 'comforting', 'comments', 'complete',
       'concerning', 'conditioned', 'connect', 'connected', 'contact',
       'continued', 'control', 'couldn', 'country', 'creator', 'credits',
       'crooked', 'crown', 'dare', 'darker', 'dated', 'davis', 'dawson',
       'dealings', 'death', 'decade', 'decide', 'decides', 'decline',
       'decorating', 'dedication', 'delight', 'descent', 'despite',
       'developed', 'devil', 'dialogs', 'dialogue', 'diary', 'different',
       'direction', 'director', 'disappears', 'disappointed', 'discerns',
       'discomforting', 'disgraceful', 'divorcing', 'do', 'dodgy',
       'doesn', 'done', 'doubt', 'down', 'dozen', 'drama', 'dream',
       'dressed', 'dropped', 'drugs', 'due', 'each', 'editing', 'effort',
       'em', 'emerald', 'encounter', 'encouraged', 'end', 'entertaining',
       'entire', 'entries', 'episode', 'even', 'ever', 'every', 'exactly',
       'excitement', 'expected', 'experience', 'experimental', 'extreme',
       'extremely', 'eyes', 'face', 'fact', 'faint', 'fallen', 'family',
       'fantasy', 'far', 'fashion', 'favorite', 'felt', 'few', 'fighting',
       'film', 'filming', 'films', 'find', 'first', 'fit', 'flat',
       'focuses', 'followed', 'for', 'forget', 'forward', 'four', 'fresh',
       'friends', 'from', 'fronts', 'fulfillment', 'fully', 'fun',
       'funny', 'further', 'gangstas', 'get', 'gets', 'give', 'given',
       'gives', 'giving', 'glass', 'go', 'goes', 'going', 'good', 'got',
       'grandma', 'graphic', 'great', 'grenier', 'grew', 'grown', 'guard',
       'guards', 'guest', 'guided', 'gunsmoke', 'gut', 'habitat', 'hacks',
       'had', 'halliwell', 'hand', 'happened', 'happening', 'happy',
       'hard', 'hardcore', 'harvey', 'has', 'have', 'having', 'he',
       'hearted', 'hell', 'her', 'here', 'hero', 'high', 'his', 'home',
       'hooked', 'hosts', 'hot', 'how', 'huge', 'human', 'hunt', 'idea',
       'if', 'ignore', 'image', 'imperioli', 'impressed', 'in',
       'inhabits', 'injustice', 'inmates', 'innovative', 'instead',
       'interesting', 'into', 'inwards', 'irish', 'is', 'it', 'italians',
       'its', 'jake', 'jewel', 'johanson', 'jumped', 'just', 'kane',
       'keitel', 'kid', 'kids', 'kill', 'killer', 'know', 'knowledge',
       'lack', 'lame', 'last', 'latinos', 'laughed', 'laughter', 'least',
       'leave', 'less', 'let', 'lets', 'levels', 'life', 'light',
       'likable', 'like', 'liked', 'lines', 'little', 'live', 'll',
       'loneliness', 'look', 'looking', 'looks', 'love', 'luck', 'lukas',
       'luxurious', 'made', 'main', 'mainly', 'mainstream', 'make',
       'makes', 'making', 'managed', 'mannered', 'many', 'master',
       'masterful', 'match', 'mattei', 'maximum', 'may', 'me',
       'meaningless', 'mediocrity', 'meet', 'mentioned', 'mess',
       'michael', 'middle', 'midgets', 'mildly', 'mistake', 'mom',
       'money', 'more', 'most', 'mother', 'movie', 'movies', 'mr',
       'murals', 'muslims', 'must', 'my', 'nasty', 'need', 'never', 'new',
       'next', 'nice', 'nickel', 'nickname', 'no', 'noble', 'not', 'now',
       'obsessives', 'of', 'off', 'offers', 'oh', 'ok', 'old', 'ole',
       'on', 'one', 'only', 'opera', 'or', 'order', 'original', 'orton',
       'oswald', 'other', 'our', 'out', 'outlet', 'own', 'oz', 'pace',
       'pacing', 'painfully', 'painted', 'parents', 'particularly', 'pat',
       'paul', 'penitentary', 'people', 'performance', 'performances',
       'performed', 'person', 'petter', 'picture', 'pictures', 'piece',
       'place', 'play', 'played', 'playing', 'plays', 'plot', 'plus',
       'point', 'points', 'polari', 'portrait', 'positive', 'power',
       'prada', 'preachy', 'present', 'pretty', 'prevents', 'previous',
       'prison', 'privacy', 'probably', 'production', 'proof', 'pulls',
       'punches', 'quit', 'rambo', 'rarely', 'rather', 're', 'read',
       'ready', 'real', 'realism', 'realize', 'really', 'recognize',
       'references', 'regards', 'relations', 'remains', 'replace',
       'respect', 'respite', 'rest', 'resurrection', 'reviewers',
       'rhymes', 'right', 'risk', 'roles', 'romance', 'roof', 'rosario',
       'ruins', 'sacrifice', 'same', 'saw', 'say', 'says', 'scarlet',
       'scenes', 'schnitzler', 'score', 'scuffles', 'sea', 'seahunt',
       'seamless', 'section', 'security', 'see', 'seems', 'seen',
       'selected', 'selflessness', 'sense', 'senses', 'serial', 'series',
       'set', 'sets', 'sex', 'sexy', 'shady', 'she', 'sheen', 'shots',
       'show', 'shows', 'side', 'similar', 'simplistic', 'sincere',
       'sitting', 'situations', 'skills', 'slow', 'slower', 'so', 'soap',
       'sold', 'solid', 'some', 'sometimes', 'song', 'sophisticated',
       'souls', 'soundtrack', 'spend', 'spirited', 'spots', 'stages',
       'stares', 'stars', 'startling', 'state', 'steve', 'still', 'story',
       'storyline', 'street', 'struck', 'stunning', 'style', 'stylishly',
       'submit', 'success', 'such', 'suddenly', 'summer', 'superman',
       'sure', 'surface', 'surreal', 'suspected', 'sympathetic', 'taken',
       'talented', 'taste', 'tears', 'tech', 'technique', 'techniques',
       'telling', 'terribly', 'terrificly', 'than', 'thank', 'that',
       'thats', 'the', 'theater', 'their', 'them', 'theme', 'then',
       'there', 'these', 'they', 'thing', 'things', 'thinks', 'this',
       'thought', 'thriller', 'thumbs', 'time', 'times', 'timid', 'to',
       'today', 'tone', 'too', 'totally', 'touch', 'traditional',
       'transfers', 'truly', 'trust', 'tune', 'turned', 'tv',
       'unassuming', 'uncomfortable', 'under', 'unflinching', 'up', 'us',
       'use', 'variation', 've', 'very', 'view', 'viewing', 'viewpoints',
       'violence', 'visually', 'vivid', 'voices', 'vote', 'wanna', 'was',
       'waste', 'watch', 'watchable', 'watched', 'watching', 'water',
       'way', 'we', 'wears', 'week', 'weekend', 'well', 'were', 'what',
       'when', 'where', 'which', 'while', 'white', 'who', 'will',
       'williams', 'wish', 'with', 'wittier', 'witty', 'woman',
       'wonderful', 'woody', 'word', 'work', 'world', 'worst', 'worth',
       'would', 'wouldn', 'wrenching', 'writing', 'written', 'years',
       'york', 'you', 'young', 'your', 'zombie'], dtype=object)

In [27]:
tf_idf.idf_

array([2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 1.6061358 , 2.70474809, 2.29928298, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.29928298, 2.70474809, 2.70474809,
       1.6061358 , 2.70474809, 2.29928298, 2.70474809, 2.70474809,
       1.78845736, 1.09531018, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 1.2006707 , 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 1.6061358 , 2.29928298, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.29928298, 2.70474809, 2.70474809, 2.70474809,
       1.31845373, 2.29928298, 2.29928298, 2.29928298, 2.70474809,
       2.29928298, 2.29928298, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.29928298, 2.70474809,
       1.2006707 , 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 1.45198512, 1.78845736,
       2.70474809, 2.70474809, 2.01160091, 2.70474809, 2.70474809,
       2.70474809, 2.29928298, 2.70474809, 2.70474809, 2.70474809,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.29928298, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.29928298, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.29928298, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.29928298, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.29928298, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.29928298, 2.70474809,
       2.01160091, 2.29928298, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.01160091, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.01160091, 2.70474809, 2.70474809, 2.29928298,
       2.01160091, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       1.31845373, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.29928298, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.01160091, 2.70474809, 2.70474809, 2.70474809,
       2.01160091, 2.70474809, 2.70474809, 2.01160091, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 1.78845736,
       1.6061358 , 2.70474809, 2.29928298, 2.29928298, 2.70474809,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 1.6061358 ,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 1.45198512,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 1.2006707 ,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.29928298, 2.70474809, 2.70474809, 1.09531018,
       1.2006707 , 2.70474809, 2.01160091, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 1.78845736, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.29928298, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.29928298, 2.70474809,
       2.70474809, 1.78845736, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.01160091, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.01160091,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.29928298, 2.01160091, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.29928298, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 1.78845736,
       2.29928298, 2.70474809, 1.78845736, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.01160091, 2.01160091, 2.29928298,
       2.70474809, 2.01160091, 2.29928298, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.01160091, 2.70474809, 1.45198512,
       2.70474809, 2.70474809, 1.09531018, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.01160091, 2.70474809, 1.31845373,
       1.31845373, 1.78845736, 2.70474809, 1.31845373, 2.70474809,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       1.6061358 , 2.70474809, 2.29928298, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.29928298, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.29928298, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.29928298, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.01160091, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 1.31845373, 2.29928298,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 1.78845736, 2.70474809, 2.70474809, 2.70474809,
       1.78845736, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 1.6061358 ,
       2.70474809, 1.45198512, 2.70474809, 1.09531018, 2.70474809,
       2.01160091, 2.01160091, 2.70474809, 1.6061358 , 2.70474809,
       2.70474809, 1.6061358 , 2.01160091, 2.29928298, 2.70474809,
       1.09531018, 2.70474809, 2.70474809, 2.70474809, 1.45198512,
       2.29928298, 2.70474809, 1.09531018, 2.29928298, 2.70474809,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       1.78845736, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.01160091, 2.70474809, 2.29928298,
       2.29928298, 2.29928298, 2.70474809, 2.01160091, 2.29928298,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 2.70474809, 1.78845736,
       2.70474809, 2.29928298, 2.70474809, 2.29928298, 1.78845736,
       2.70474809, 1.78845736, 2.01160091, 2.70474809, 2.70474809,
       2.70474809, 1.78845736, 2.29928298, 1.78845736, 2.01160091,
       2.01160091, 1.78845736, 2.29928298, 2.70474809, 2.70474809,
       2.70474809, 2.70474809, 2.70474809, 1.31845373, 2.70474809,
       2.70474809, 2.70474809, 2.29928298, 2.70474809, 2.70474809,
       2.29928298, 2.01160091, 2.70474809, 2.70474809, 2.29928298,
       2.29928298, 2.70474809, 2.70474809, 2.70474809, 2.01160091,
       2.70474809, 1.6061358 , 2.29928298, 2.70474809, 2.70474809])

- Pros

      Info retrieval system (To pull up relative websites in search engines)
      Key word extraction -- Topic modeling (Finding important topic in a doc)
      Doc similarity

- Cons

      Sparse data
      OOV
      Hight dim
      Still not good for semantic relationship!

###Topic modeling using TFIDF Technique

In [30]:
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

# 1. Clean HTML tags out of the reviews
clean_docs = [re.sub(r'<[^>]+>', ' ', d) for d in docs]

# 2. Vectorize
tf_idf = TfidfVectorizer(
    stop_words='english',
    max_df=0.8,                      # drop words in >80% of docs
    min_df=1,
    token_pattern=r'\b[a-z]{3,}\b',  # only alphabetic tokens, 3+ chars
    lowercase=True
)
X = tf_idf.fit_transform(clean_docs)
vocab = tf_idf.get_feature_names_out()

# 3. Topic model
n_topics = 3
nmf = NMF(
    n_components=n_topics,
    random_state=42,
    init='nndsvd',
    max_iter=1000
)
W = nmf.fit_transform(X)   # (n_docs, n_topics) — topic weights per review
H = nmf.components_        # (n_topics, n_words) — word weights per topic

# 4. Top words per topic
for i, topic in enumerate(H):
    top_words = [vocab[j] for j in topic.argsort()[::-1][:8]]
    print(f"Topic {i}: {', '.join(top_words)}")

print()

# 5. Dominant topic per review
for i, row in enumerate(W):
    print(f"Review {i}: Topic {row.argmax()} (score {row.max():.2f})")

Topic 0: movie, like, old, jake, hell, gut, camp, wrenching
Topic 1: comedy, violence, thought, woody, watching, right, production, halliwell
Topic 2: film, mattei, keitel, different, people, best, acting, live

Review 0: Topic 1 (score 0.61)
Review 1: Topic 1 (score 0.63)
Review 2: Topic 1 (score 0.69)
Review 3: Topic 0 (score 0.37)
Review 4: Topic 2 (score 0.83)
Review 5: Topic 0 (score 0.47)
Review 6: Topic 0 (score 0.25)
Review 7: Topic 1 (score 0.24)
Review 8: Topic 2 (score 0.86)
Review 9: Topic 0 (score 0.55)

##2.5.Custom Feature Extraction

- No of positive and negative words
- RAtio of positive and negative words
- Word counting
- Char Counting